language: node_js
node_js:
    - 7.10
services: 
  - mongodb
before_script:
  - npm install
  - npm run pretest
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user: "travis", pwd: "test" });'
script: npm test