version: "3"
services:
  mongodb:
    image: mongo
  calendarapp:
    build: ../.
    ports:
      - "5000:5000"
    depends_on:
      - "mongodb"
    command: [ "npm", "start"]
    env_file: ../.env
    volumes:
      - ../secret/:/app/secret