version: "3"
services:
  mongodb:
    image: mongo
  calendarapp:
    build: ../../.
    depends_on:
      - "mongodb"
    command: ["npm", "start"]
    # Include the env file to load to the app
    env_file: ../../.env
    # Make sure to include the JSON service token and reference it's path in the ENV file
    volumes:
      - ../../secret/:/app/secret
  balancer:
    image: nginx:latest
    # Update accordingly
    ports:
      - "5001:80"
      - "5002:443"
    volumes:
      - ./confs/:/etc/nginx/conf.d/:ro
    depends_on:
      - "calendarapp"